name: Build FFmpeg for Media3

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        unzip -q android-ndk-r25c-linux.zip
        echo "NDK_PATH=$(pwd)/android-ndk-r25c" >> $GITHUB_ENV

    - name: Clone Media3
      run: |
        git clone https://github.com/androidx/media.git
        cd media
        git checkout 1.6.1
        echo "FFMPEG_MODULE_PATH=$(pwd)/libraries/decoder_ffmpeg/src/main" >> $GITHUB_ENV

    - name: Clone FFmpeg
      run: |
        git clone git://source.ffmpeg.org/ffmpeg
        cd ffmpeg
        git checkout release/6.0
        echo "FFMPEG_PATH=$(pwd)" >> $GITHUB_ENV

    - name: Enable Video Decoders (H.264/HEVC)
      run: |
        # 使用 sed 命令自动在脚本里加上开启 H264 的参数
        sed -i 's/--disable-decoders \\/--disable-decoders \\\n    --enable-decoder=h264 \\\n    --enable-decoder=hevc \\/g' $FFMPEG_MODULE_PATH/jni/build_ffmpeg.sh
        cat $FFMPEG_MODULE_PATH/jni/build_ffmpeg.sh | grep "enable-decoder=h264"

    - name: Build FFmpeg
      run: |
        cd $FFMPEG_MODULE_PATH/jni
        export HOST_PLATFORM="linux-x86_64"
        export ANDROID_ABI=21
        export ENABLED_DECODERS=(aac ac3 mp3 flac h264 hevc)
        ./build_ffmpeg.sh $FFMPEG_MODULE_PATH $NDK_PATH $HOST_PLATFORM ${ANDROID_ABI} ${ENABLED_DECODERS[@]}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-so-files
        # 把编译好的 decoder_ffmpeg 整个文件夹打包给你
        path: media/libraries/decoder_ffmpeg/

